#!/bin/bash

conda create --name picachooser
conda activate picachooser
#conda install nomkl 'numpy>=1.16' scipy matplotlib pandas statsmodels scikit-learn nibabel pyfftw numba pyqt pyqtgraph tensorflow keras
conda install pip=19.3.1 scipy=1.4.1 numpy=1.17.3 pillow=7.0.0 nibabel=2.5.1 pandas=0.25.3 pyqtgraph=0.10.0

