#!/bin/bash

conda create --name picachooser
conda activate picachooser
mamba install \
    pip \
    scipy \
    numpy \
    pillow \
    nibabel \
    pandas \
    pyqt \
    pyqt5-sip \
    "pyqtgraph<0.13"

