#!/bin/bash

#PICAchooser \
#    groupmelodic \
#    --backgroundfile /Volumes/skohut/ss_blood_flow/melodic/rapidtided_0p15_cathinone/25mode/mean.nii.gz \
#    --ICfile /Volumes/skohut/ss_blood_flow/melodic/rapidtided_0p15_cathinone/25mode/melodic_IC.nii.gz \
#    --ICmask /Volumes/skohut/ss_blood_flow/melodic/rapidtided_0p15_cathinone/25mode/mask.nii.gz \
#    --timecoursefile /Volumes/skohut/ss_blood_flow/melodic/rapidtided_0p15_cathinone/25mode/melodic_mix \
#    --ICstatsfile /Volumes/skohut/ss_blood_flow/melodic/rapidtided_0p15_cathinone/25mode/melodic_ICstats

PICAchooser \
    groupmelodic \
    --melodicdir /Volumes/skohut/bids_94T/ss_blood_flow/melodic/rapidtided_0p15_cathinone/25mode \
    --verbose
