#!/bin/bash

PICAchooser \
    melodic \
    --featdir /Users/frederic/Dropbox_PHC/MR_data/gradertest/079N_resting_visit1.feat \
    --melodicdir /Users/frederic/Dropbox_PHC/MR_data/gradertest/079N_resting_visit1.feat/filtered_func_data.ica \
    --usereferencefile \
    --ICreffile /Users/frederic/Dropbox_PHC/MR_data/gradertest/079N_resting_visit1.feat/filtered_func_data.ica/melodic_IC.nii.gz \
    --refdisplaythresh 0.5 \
    --debug
