#!/usr/bin/env python

import numpy as np

import picachooser.util as pica_util

valuelist0 = np.array([], dtype=int)
valuelist1 = np.array([5, 10, 15, 20], dtype=int)

numelements = 30

print(f"{valuelist0=}")
print(f"{valuelist1=}")
for testvalue in [0, 3, 5, 6, 10, 27]:
    forwardvalue0 = pica_util.nextmatch(testvalue, valuelist0, backwards=False, debug=True)
    forwardvalue1 = pica_util.nextmatch(testvalue, valuelist1, backwards=False, debug=True)
    backwardvalue0 = pica_util.nextmatch(testvalue, valuelist0, backwards=True, debug=True)
    backwardvalue1 = pica_util.nextmatch(testvalue, valuelist1, backwards=True, debug=True)
    print(
        f"{testvalue=}: {forwardvalue0=}, {forwardvalue1=}, {backwardvalue0=}, {backwardvalue1=}"
    )
