#!/bin/csh -f

docker build . -t fredericklab/picachooser:1.0.0rc3

docker push fredericklab/picachooser:1.0.0rc3
docker pull fredericklab/picachooser:1.0.0rc3

docker run -it picachooser bash

# allow network connections in Xquartz Security settings
xhost +
xhost +si:localuser:picachooser

# Allow your local user access via xhost: xhost +SI:localuser:picachooser and create a similar user with docker run option: --user=$(id -u):$(id -g)
docker run \
    --network host\
    --volume=/Users/frederic:/Users/frederic \
    -it \
    -e DISPLAY=192.168.7.146:0 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -u picachooser fredericklab/picachooser:1.0.0rc3 \
    PICAchooser \
        /Users/frederic/Documents/MR_data/gradertest/079N_resting_visit1.feat \
        /Users/frederic/Documents/MR_data/gradertest/079N_resting_visit1.feat/filtered_func_data.ica \
        fix
